baseurl = "https://www.ruoranepi.com/"
languageCode = "en-us"
title = "ruoran's notes"
#theme = "hugo-lithium-tag"
  # Update last chage date:
      # /Users/RLi/Documents/GitHub/blog/themes/hugo-lithium-tag/layouts/partials/footer.html 
      
theme = "hugo-base16-theme-master"
#copyright = "&copy; Ruoran Li 2019"

googleAnalytics = "UA-117912987-2"
disqusShortname = "https-ruoranepi-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsuseclasses = true

hasCJKLanguage=true

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:slug/"


[params]
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

