baseurl = "https://ruoranepi.netlify.com/"
languageCode = "en-us"
title = "Ruoran Li"
theme = "hugo-lithium-tag"
  # Update last chage date:
      # /Users/RLi/Documents/GitHub/blog/themes/hugo-lithium-tag/layouts/partials/footnote.html 

googleAnalytics = "UA-114721555-1"
disqusShortname = "https-ruoranepi-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:slug/"

 [[menu.main]]
     name = "tags"
     url = "/tags/"
     weight = 2
 [[menu.main]]
     name = "categories"
     url = "/categories/"
     weight = 1
[[menu.main]]
#    identifier = "research"
    name = "research"
    url = "/research/"
    weight = 3
[[menu.main]]
#    identifier = "teaching"
    name = "teaching"
    url = "/teaching/"
    weight = 4
[[menu.main]]
#    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 5

[params]
    description = "Grad student in epi."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

