[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.39"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
# Redirect default Netlify subdomain to primary domain
https://ruoranepi.netlify.com/* https://www.ruoranepi.com/:splat 301!
